language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

install:
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - make test

matrix:
  fast_finish: true
  allow_failures:
    - python: 2.6
    - python: 3.2

script: coverage run setup.py test

after_success:
 - coveralls
