language: python

python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - make test

script: coverage run setup.py test

after_success:
 - coveralls
